Project ArtStar_Notion_Framework {
  database_type: 'Notion.so'
  Note: '''
  # ERD for Artist/Gallery System Framework in Notion

  DBML docs: https://www.dbml.org/docs/#project-definition

  All tables will be pre-pended in Notion with either "ArtStar::" or "AS::" in order to facilitate easy selection in Relationships.

  __Formmating Notes__

  * relationship __one-to-many__ current table w/ table2.column = [ref: < table2.column]
  * relationship __many-to-one__ current table w/ table2.column = [ref: > table2.column]
  * relationship __one-to-one or many-to-many__ current table w/ table2.column = [ref: - table2.column]
  * column notes = [note:'']

  ## Push to dbdocs.io
  dbdocs build art-star.dbml
  '''
}

Table format_examples {
  select_example select [
    note: '
    💸 1 = processing, 
    ✔️ 2 = shipped, 
    ❌ 3 = cancelled,
    😔 4 = refunded
  ']
  column_note varchar [
    note: 'this is a note']
  // this is a comment, not specific to a column
  // but can be used anywhere as needed
  Note: 'Examples of Table and Column formatting.'
} 

// ------------------ Artworks
Table Artworks {
  // ===== general artwork info =====
  Name text [pk]
  Images file_media [
    note: 'multi-file upload, for use in Rollups']
  YearMade text 
  Media multi_select [
    note: 'acrylic, cold wax, encaustic, photograph, ink, oil, wax']
  Substrate select [
    note: 'on canvas, on canvas sheet, on wood panel, on paper']
  Height number [
    note: 'integer in inches. cm will be auto-calculated']
  Width number [
    note: 'integer in inches. cm will be auto-calculated']
  Depth number [
    note: 'integer in inches. cm will be auto-calculated']
  PriceCalc number [
    note: 'used in Price formula: Height x Width x PriceCalc']
  AutoPrice formula [
    note: 'round(prop("Height") * prop("Width") * prop("PriceCalc"))']
  ManualPrice number [
    note: 'Used to override `AutoPrice` if want to set specific price']
  OverrideAutoPrice checkbox [
    note: 'check if want `ManualPrice` to be used in display formulas instead of `AutoPrice`']
  DisplayPrice formula [
    note: 'Needed for Rollup sum in Deals: prop("OverrideAutoPrice") ? prop("ManualPrice") : prop("AutoPrice")'
  ]
  
  // ===== meta data =====
  Series relationship [
    ref: > Series.Name]
  Tags relationship [
    ref: < Tags.Name]
  Colors multi_select [
    note: 'black, blue, brown, orange, pink, red, white, yellow']
  
  // ===== CRM connections =====
  Collectors relationship [
    ref: > contacts.Name]
  Galleries relationship [
    ref: > organizations.Name]
  Exhibitions relationship [
    ref: - Exhibitions.Name]
  Deals relationship [
    ref: - Deals.Name, note: '']

  // ===== Social Media =====
  IncludeYear checkbox [
    note: 'used in `ArtworkCaption` display formula']
  IncludeInches checkbox [
    note: 'used in `ArtworkCaption` display formula']
  IncludeCM checkbox [
    note: 'used in `ArtworkCaption` display formula']
  IncludePrice checkbox [
    note: 'used in `ArtworkCaption` display formula']

  // ===== Formulas =====
  DimensionsInches formula [
    note: 'Creates inches display: if(empty(prop("Height")), "", concat(format(prop("Height")), " x ", format(prop("Width")), if(empty(prop("Depth")), "", concat(" x ", format(prop("Depth")))), " in"))']
  DimensionsCM formula [
    note: 'Creates centimeter display: if(empty(prop("Height")), "", concat(format(multiply(2.54, prop("Height"))), " x ", format(multiply(2.54, prop("Width"))), if(empty(prop("Depth")), "", concat(" x ", format(multiply(2.54, prop("Depth"))))), " cm"))']
  ArtworkCaption formula [
    note: '''Full caption for display and copy/paste: concat("'" + prop("name") + "'" + if(prop("IncludeYear"), "\\n" + prop("year"), "") + if(empty(prop("media")), "", "\\n" + prop("media")) + " " + prop("Substrate") + if(prop("IncludeInches"), "\\n" + prop("DimensionsInches"), "") + if(prop("IncludeCM"), "\\n" + prop("DimensionsCM"), "") + if(prop("IncludePrice"), prop("OverrideAutoPrice") ? ("\\n$" + format(prop("ManualPrice")) + ".00") : ("\\n" + prop("AutoPrice")), "") + "\\n")''']

  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']

  Note: 'Artwork Images and data for tracking and connecting.'
}

// ------------------ Series
Table Series {
  Name text [pk]
  Summary text
  DateSeriesStared date
  DateSeriesended date

  // ===== meta data =====
  SeriesArtist person [
    note: 'select from Members and Guests']
  Tags relationship [
    ref: < Tags.Name]
  Artworks relationship [
    ref: < Artworks.Name]

  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Tags
Table Tags {
  Name text [pk]
  Summary text
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Contacts
Table contacts {
  Name text [pk]
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Organizations
Table organizations {
  Name text [pk]

  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']

  Note: 'Galleries, Museums, Non-profits, and all Businesses wanting to be tracked and connected.'
}

// ------------------ Exhibitions
Table Exhibitions {
  Name text [pk]
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Deals
Table Deals {
  Name text [pk]
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

