Project ArtStar_Notion_Framework {
  database_type: 'Notion.so'
  Note: '''
  # ERD for Artist/Gallery Management & CRM System Framework in Notion

  DBML docs: https://www.dbml.org/docs/#project-definition

  All tables will be pre-pended in Notion with either "ArtStar::" or "AS::" in order to facilitate easy selection in Relationships.

  __Formmating Notes__

  * relationship __one-to-many__ current table w/ table2.column = [ref: < table2.column]
  * relationship __many-to-one__ current table w/ table2.column = [ref: > table2.column]
  * relationship __one-to-one or many-to-many__ current table w/ table2.column = [ref: - table2.column]
  * column notes = [note:'']

  ## Push to dbdocs.io
  $ dbdocs build art-star.dbml
  '''
}

// ------------------ Artworks
Table Artworks {
  // ===== general artwork info =====
  Name text [pk]
  Artist person [
    note: 'select from Members and Guests']
  Images file_media [
    note: 'multi-file upload, for use in Rollups']
  YearMade text 
  Media multi_select [
    note: 'acrylic, cold wax, encaustic, photograph, ink, oil, wax']
  Substrate select [
    note: 'on canvas, on canvas sheet, on wood panel, on paper']
  Height number [
    note: 'integer in inches. cm will be auto-calculated']
  Width number [
    note: 'integer in inches. cm will be auto-calculated']
  Depth number [
    note: 'integer in inches. cm will be auto-calculated']
  PriceCalc number [
    note: 'used in Price formula: Height x Width x PriceCalc']
  AutoPrice formula [
    note: 'round(prop("Height") * prop("Width") * prop("PriceCalc"))']
  ManualPrice number [
    note: 'Used to override `AutoPrice` if want to set specific price']
  OverrideAutoPrice checkbox [
    note: 'check if want `ManualPrice` to be used in display formulas instead of `AutoPrice`']
  DisplayPrice formula [
    note: 'Needed for Rollup sum in Deals: prop("OverrideAutoPrice") ? prop("ManualPrice") : prop("AutoPrice")'
  ]
  
  // ===== meta data =====
  Series relationship [
    ref: > Series.Name]
  Tags relationship [
    ref: < Tags.Name]
  Colors multi_select [
    note: 'black, blue, brown, orange, pink, red, white, yellow']
  
  // ===== CRM connections =====
  Collectors relationship [
    ref: > Contacts.Name]
  Galleries relationship [
    ref: > Organizations.Name]
  Exhibitions relationship [
    ref: - Exhibitions.Name]
  Deals relationship [
    ref: - Deals.Name, note: '']

  // ===== Social Media =====
  IncludeYear checkbox [
    note: 'used in `ArtworkCaption` display formula']
  IncludeInches checkbox [
    note: 'used in `ArtworkCaption` display formula']
  IncludeCM checkbox [
    note: 'used in `ArtworkCaption` display formula']
  IncludePrice checkbox [
    note: 'used in `ArtworkCaption` display formula']

  // ===== Formulas =====
  DimensionsInches formula [
    note: 'Creates inches display: if(empty(prop("Height")), "", concat(format(prop("Height")), " x ", format(prop("Width")), if(empty(prop("Depth")), "", concat(" x ", format(prop("Depth")))), " in"))']
  DimensionsCM formula [
    note: 'Creates centimeter display: if(empty(prop("Height")), "", concat(format(multiply(2.54, prop("Height"))), " x ", format(multiply(2.54, prop("Width"))), if(empty(prop("Depth")), "", concat(" x ", format(multiply(2.54, prop("Depth"))))), " cm"))']
  ArtworkCaption formula [
    note: '''Full caption for display and copy/paste: concat("'" + prop("name") + "'" + if(prop("IncludeYear"), "\\n" + prop("year"), "") + if(empty(prop("media")), "", "\\n" + prop("media")) + " " + prop("Substrate") + if(prop("IncludeInches"), "\\n" + prop("DimensionsInches"), "") + if(prop("IncludeCM"), "\\n" + prop("DimensionsCM"), "") + if(prop("IncludePrice"), prop("OverrideAutoPrice") ? ("\\n$" + format(prop("ManualPrice")) + ".00") : ("\\n" + prop("AutoPrice")), "") + "\\n")''']

  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']

  Note: 'Artwork Images and data for tracking and connecting.'
}

// ------------------ Series
Table Series {
  Name text [pk]
  Summary text
  DateSeriesStared date
  DateSeriesended date

  // ===== meta data =====
  SeriesArtist person [
    note: 'select from Members and Guests']
  Tags relationship [
    ref: < Tags.Name]
  Artworks relationship [
    ref: < Artworks.Name]

  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Tasks
Table Tasks {
  Name text [pk]
  AssignedTo person [
    note: 'select from Members and Guests']
  DueDate date
  TickleDate date
  CompletedDate date
  CompletedBy person [
    note: 'select from Members and Guests']
  Status select
  Context select
  Priority select
  IfWaitingWhy text
  TimeRequired number
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Tags
Table Tags {
  Name text [pk]
  Summary text
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Contacts
Table Contacts {
  Name text [pk, 
    note: 'Full Name so we do not have to concatenate via formulas for display']
  FirstName text
  LastName text [
    note: 'Exists so we can sort on Last Name']
  Website url
  Instagram url
  LinkedIn url
  Email email [
    note: 'May be necessary for additional email fields.']
  Phone phone [
    note: 'May be necessary for additional phone fields.']
  Street text
  City text
  State text
  Zip text
  Country select 
  Source select [
    note: 'Where was this contact made?']
  
  // ===== CRM & Relationships =====
  Artworks relationship [
    ref: < Artworks.Name, 
    note: 'Artworks this person owns.']
  Organizations relationship [
    ref: > Organizations.Name, 
    note: 'Optional. Where this person works.']
  Tasks relationship [
    ref: < Tasks.Name, 
    note: 'Optional tasks associated with this person.']
  Deals relationship [
    ref: < Deals.Name, 
    note: 'Deals this person is related to.']
  ReferredBy relationship [
    ref: - Contacts.Name,
    note: 'Who referred this person to us?']
  Referrals relationship [
    ref: < Contacts.Name, 
    note: 'Who did this person refer to us?']
  Exhibitions relationship [
    ref: < Exhibitions.Name, 
    note: 'Exhibitions & Shows related to this person.']

  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Organizations
Table Organizations {
  Name text [pk]
  ServiceIndustry multi_select
  Website url
  Instagram url
  Email email [
    note: 'May be necessary for additional email fields.']
  Phone phone [
    note: 'May be necessary for additional phone fields.']
  Street text
  City text
  State text
  Zip text
  Country select 

  // ===== CRM & Relationships =====
  Artworks relationship [
    ref: < Artworks.Name, 
    note: 'Artworks related to this Org.']
  Staff relationship [
    ref: < Contacts.Name, 
    note: 'People related to this Org.']
  Tags relationship [
    ref: < Tags.Name]
  Tasks relationship [
    ref: < Tasks.Name, 
    note: 'Optional Tasks associated with this Org.']
  Deals relationship [
    ref: < Deals.Name, 
    note: 'Deals this Org is related to.']
  Exhibitions relationship [
    ref: < Exhibitions.Name, 
    note: 'Exhibitions & Shows related to this Org.']



  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']

  Note: 'Galleries, Museums, Non-profits, and all Businesses wanting to be tracked and connected.'
}

// ------------------ Exhibitions
Table Exhibitions {
  Name text [pk]
  Artist person [
    note: 'select from Members and Guests']
  Website url
  Hashtags multi_select
  ShowDates date [note: 'Range. Include Start and End dates']
  SubmissionDue date

  // ===== Relationships =====
  Artworks relationship [
    ref: < Artworks.Name, 
    note: 'Artworks related to this Exhibition.']
  Contact relationship [
    ref: < Contacts.Name, 
    note: 'People related to this Exhibition.']
  Tags relationship [
    ref: < Tags.Name]
  Tasks relationship [
    ref: < Tasks.Name, 
    note: 'Optional Tasks associated with this Exhibition.']
  Organizations relationship [
    ref: < Organizations.Name, 
    note: 'Where is this Exhibition?']
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

// ------------------ Deals
Table Deals {
  Name text [pk]
  AssignedTo person [
    note: 'select from Members and Guests']
  Stage multi_select
  Type multi_select
  Discount number [
    note: 'Enter integer. Format as %']
  Tax number [
    note: 'Enter integer. Format as %. Leave empty if not needed.']
  CloseDate date
  WonLostReason text

  // ===== CRM & Relationships =====
  Artworks relationship [
    ref: < Artworks.Name, 
    note: 'Artworks related to this Deal.']
  ArtworksTotal rollup [
    note: 'SUM Rollup of Artworks relationship']
  Contact relationship [
    ref: < Contacts.Name, 
    note: 'People related to this Deal.']
  Tags relationship [
    ref: < Tags.Name]
  Tasks relationship [
    ref: < Tasks.Name, 
    note: 'Optional Tasks associated with this Deal.']
  Organizations relationship [
    ref: < Organizations.Name, 
    note: 'Org(s) related to this Deal.']

  // ===== Formulas =====
  DealWDiscount formula [
    note: 'prop("ArtworksTotal") - prop("ArtworksTotal") * prop("Discount")']
  DealTotal formula [
    note: 'Includes tax : prop("DealWDiscount") + prop("DealWDiscount") * prop("Tax")']
  
  // ===== Created and Modified =====
  Created created_time [default: 'now()']
  CreatedBy created_by [default: 'current user']
  Modified last_edited_time [default: 'now()']
  ModifiedBy last_edited_by [default: 'current user']
}

